"use client";

import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight, Check, Minus, Plus, ShoppingBag, Sparkles } from "lucide-react";
import type { StorefrontCartPageProps, StorefrontCheckoutProps, StorefrontCollectionProps, StorefrontContentPageProps, StorefrontOrderProps, StorefrontProductProps, StorefrontSearchProps } from "@jelly/storefront-themes";

const setting = (settings: Record<string, unknown>, path: string, fallback: string) => { const value = path.split(".").reduce<unknown>((current, key) => current && typeof current === "object" ? (current as Record<string, unknown>)[key] : undefined, settings); return typeof value === "string" ? value : fallback; };

export function SharedCollectionPage({ products, categories, selectedCategory, allHref, categoryHref, settings }: StorefrontCollectionProps) {
  const ratio = setting(settings, "productCard.imageRatio", "portrait"); const cardStyle = setting(settings, "productCard.style", "minimal"); const alignment = setting(settings, "productCard.alignment", "left"); const showBrand = settings.productCard && typeof settings.productCard === "object" && (settings.productCard as Record<string, unknown>).showBrand === false ? false : true;
  return <main className="shop-page text-[var(--store-text)]"><header className="shop-title"><span className="text-[10px] font-extrabold uppercase tracking-[.12em] text-[var(--store-accent)]">Made for good days</span><h1>Shop everything</h1><p>{products.length ? `${products.length} small-batch treats, ready when you are.` : "This collection is being prepared. Check back soon."}</p></header>{products.length ? <><nav className="category-tabs" aria-label="Product categories"><Link className={!selectedCategory ? "active" : undefined} href={allHref}>All</Link>{categories.map((category) => <Link className={selectedCategory === category ? "active" : undefined} key={category} href={categoryHref(category)}>{category}</Link>)}</nav><div className="shop-grid grid grid-cols-2 gap-[clamp(15px,2.5vw,34px)] md:grid-cols-3 lg:grid-cols-4">{products.map((product) => <article key={product.id} className={`group product-card-${cardStyle} text-${alignment}`}><Link href={product.href} className={`relative block overflow-hidden rounded-[28px] bg-[var(--theme-surface)] ${ratio === "square" ? "aspect-square" : ratio === "natural" ? "aspect-auto" : "aspect-[4/5]"}`}><Image src={product.imageUrl} alt={product.name} width={720} height={900} className="h-full w-full object-cover transition duration-500 group-hover:scale-[1.035]" />{(product.lowStock || product.soldOut) ? <span className="absolute left-3.5 top-3.5 rounded-full bg-white/92 px-3 py-1.5 text-[9px] font-black uppercase tracking-[.07em]">{product.soldOut ? "Sold out" : "Limited stock"}</span> : null}<span className="absolute bottom-3.5 right-3.5 grid size-9 place-items-center rounded-full bg-white opacity-0 shadow-lg transition group-hover:opacity-100"><ArrowUpRight size={14} /></span></Link><div className="flex items-start justify-between gap-5 px-1 py-4"><div>{showBrand ? <p className="text-[9px] font-black uppercase tracking-[.12em] text-[var(--theme-muted-text)]">{product.category}</p> : null}<h2 className="mt-1.5 font-[var(--theme-font-heading,Georgia)] text-[19px]">{product.name}</h2></div><p className="text-[12px] font-black">{product.price}</p></div></article>)}</div></> : null}</main>;
}

export function SharedProductPage({ product, price, availableText, options, backHref, variantAvailable, requiredMissing, added, onSelectOption, onAddToCart }: StorefrontProductProps) {
  return <main className="product-page text-[var(--store-text)]"><Link href={backHref} className="product-back"><ArrowLeft size={16} />Back to shop</Link><div className="product-detail"><div className="product-gallery"><Image src={product.imageUrl} alt={product.name} fill priority sizes="(max-width: 800px) 100vw, 50vw" /><span className="gallery-sticker"><Sparkles size={16} />Hand finished</span></div><div className="product-copy"><span>{product.category}</span><h1>{product.name}</h1><p className="product-price">{price}</p><p className="product-description">{product.description}</p><div className="variant-card">{options.map((option) => <fieldset key={option.id}><legend>{option.name}{option.required ? " *" : ""}</legend><div className="mt-2 flex flex-wrap gap-2">{option.values.map((value) => <button type="button" key={value.id} onClick={() => onSelectOption(option.id, value.id)} className={value.selected ? "rounded-full border border-[var(--store-text)] bg-[var(--store-text)] px-3 py-2 text-xs font-bold text-[var(--store-bg)]" : "rounded-full border border-black/15 px-3 py-2 text-xs font-bold"}>{value.label}{value.priceAdjustment ? ` +${value.priceAdjustment}` : ""}</button>)}</div></fieldset>)}{options.length === 0 ? <p className="text-xs opacity-70">Standard</p> : null}<p className="text-xs font-bold opacity-70">{availableText}</p></div><button type="button" className="store-button wide" disabled={!variantAvailable || requiredMissing} onClick={onAddToCart}>{added ? <><Check size={18} />Added to bag</> : <><ShoppingBag size={18} />Add to cart</>}</button></div></div></main>;
}

export function SharedSearchPage({ query, results, shopHref, settings }: StorefrontSearchProps) {
  const ratio = setting(settings, "productCard.imageRatio", "portrait");
  return <main className="shop-page text-[var(--store-text)]"><header className="shop-title"><span className="text-[10px] font-extrabold uppercase tracking-[.12em] text-[var(--store-accent)]">Search the shop</span><h1>{query ? `Results for “${query}”` : "Find something lovely"}</h1><p>{results.length ? `${results.length} match${results.length === 1 ? "" : "es"} found.` : "No products matched that search."}</p></header>{results.length ? <div className="shop-grid grid grid-cols-2 gap-[clamp(15px,2.5vw,34px)] md:grid-cols-3 lg:grid-cols-4">{results.map((product) => <article key={product.id} className="group"><Link href={product.href} className={`relative block overflow-hidden rounded-[28px] bg-[var(--theme-surface)] ${ratio === "square" ? "aspect-square" : ratio === "natural" ? "aspect-auto" : "aspect-[4/5]"}`}><Image src={product.imageUrl} alt={product.name} width={720} height={900} className="h-full w-full object-cover transition duration-500 group-hover:scale-[1.035]" /></Link><div className="flex items-start justify-between gap-5 px-1 py-4"><h2 className="font-[var(--theme-font-heading,Georgia)] text-[19px]">{product.name}</h2><p className="text-[12px] font-black">{product.price}</p></div></article>)}</div> : <Link href={shopHref} className="button button-secondary">Browse all products</Link>}</main>;
}

export function SharedCartPage({ lines, subtotal, shopHref, checkoutHref, onDecrease, onIncrease }: StorefrontCartPageProps) {
  return <main className="shop-page text-[var(--store-text)]"><header className="shop-title"><span className="text-[10px] font-extrabold uppercase tracking-[.12em] text-[var(--store-accent)]">Your selection</span><h1>Your cart</h1><p>{lines.length ? "Review your items before checkout." : "Your bag is waiting for something lovely."}</p></header>{lines.length ? <><div className="cart-lines">{lines.map((line) => <div className="cart-line" key={line.id}><div className="cart-thumb"><Image src={line.imageUrl} alt="" fill sizes="90px" /></div><div className="cart-line-copy"><b>{line.productName}</b><span>{line.variantName}</span>{line.options.map((option) => <small key={option}>{option}</small>)}<div className="quantity-control"><button type="button" aria-label={`Remove one ${line.productName}`} onClick={() => onDecrease(line.id)}><Minus size={14} /></button><span>{line.quantity}</span><button type="button" aria-label={`Add one ${line.productName}`} disabled={!line.canIncrease} onClick={() => onIncrease(line.id)}><Plus size={14} /></button></div></div><strong>{line.lineTotal}</strong></div>)}</div><div className="cart-summary"><div><span>Subtotal</span><b>{subtotal}</b></div><p>Shipping is calculated at checkout.</p><Link href={checkoutHref} className="button button-primary">Checkout</Link></div></> : <Link href={shopHref} className="button button-secondary">Keep browsing</Link>}</main>;
}

export function SharedCheckoutPage({ children }: StorefrontCheckoutProps) { return <div className="storefront-checkout-page">{children}</div>; }
export function SharedOrderPage({ children }: StorefrontOrderProps) { return <div className="storefront-order-page">{children}</div>; }
export function SharedContentPage({ children }: StorefrontContentPageProps) { return <div className="storefront-content-page">{children}</div>; }
