ALTER TABLE "Product"
  ADD COLUMN IF NOT EXISTS "primaryCategoryId" TEXT,
  ADD COLUMN IF NOT EXISTS "additionalCategoryIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS "brandId" TEXT,
  ADD COLUMN IF NOT EXISTS "collectionIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS "options" JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS "inventoryOptionIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS "categoryMetadata" JSONB,
  ADD COLUMN IF NOT EXISTS "brandMetadata" JSONB,
  ADD COLUMN IF NOT EXISTS "collectionMetadata" JSONB NOT NULL DEFAULT '[]'::jsonb;
