/* eslint-disable @next/next/no-img-element -- theme assets are namespaced static presentation assets. */
import type { ThemeShellComponents } from "../../types.js";

const text = (settings: Record<string, unknown>, path: string, fallback: string) => {
  const value = path.split(".").reduce<unknown>((current, key) => current && typeof current === "object" ? (current as Record<string, unknown>)[key] : undefined, settings);
  return typeof value === "string" ? value : fallback;
};
const enabled = (settings: Record<string, unknown>, path: string, fallback = true) => {
  const value = path.split(".").reduce<unknown>((current, key) => current && typeof current === "object" ? (current as Record<string, unknown>)[key] : undefined, settings);
  return typeof value === "boolean" ? value : fallback;
};

export const boutiqueShellComponents: ThemeShellComponents = {
  Layout: ({ header, footer, cart, children, settings }) => <div className={`jelly-boutique-shell jelly-boutique-layout-${text(settings, "layout.backgroundStyle", "paper")}`}>{header}<main className="jelly-boutique-content">{children}</main>{footer}{cart}</div>,
  Header: ({ store, navigation, cartCount, settings, onCartOpen }) => <header className={`jelly-boutique-header jelly-boutique-header-${text(settings, "header.variant", text(settings, "header.style", "editorial"))} ${enabled(settings, "header.sticky", false) ? "jelly-boutique-header-sticky" : ""}`}>
    {enabled(settings, "header.announcementEnabled") ? <p className="jelly-boutique-announcement">{text(settings, "header.announcement", "Small-batch goods, thoughtfully made.")}</p> : null}
    <div className="jelly-boutique-header-main"><a href={`/${store.slug}`} className={`jelly-boutique-wordmark jelly-boutique-logo-${text(settings, "header.logoSize", "medium")}`}>{store.name}</a><nav aria-label="Store navigation" className={`jelly-boutique-nav jelly-boutique-nav-${text(settings, "header.navigationAlignment", "center")}`}>{navigation.filter((item) => enabled(settings, "header.showSearch", true) || !item.href.endsWith("/search")).map((item) => <a key={item.href} href={item.href}>{item.label}</a>)}</nav>{enabled(settings, "header.showCart", true) ? <button type="button" onClick={onCartOpen} aria-label={`Open cart with ${cartCount} items`} className="jelly-boutique-cart">Bag <span>{cartCount}</span></button> : null}</div>
  </header>,
  Footer: ({ store, settings }) => <footer className={`jelly-boutique-footer jelly-boutique-footer-${text(settings, "footer.style", "split")} jelly-boutique-footer-align-${text(settings, "footer.alignment", "left")}`}><div><p className="jelly-boutique-kicker">From the studio</p><strong>{store.name}</strong><p>{store.tagline}</p></div>{enabled(settings, "footer.showNewsletter") ? <div><p className="jelly-boutique-kicker">Letters</p><p>Occasional notes on objects, makers and the season.</p></div> : null}{enabled(settings, "footer.showSocialLinks") ? <div className="jelly-boutique-social"><a href="#instagram">Instagram</a><a href="#journal">Journal</a></div> : null}<small>{text(settings, "footer.copyright", `© ${store.name}`)}</small></footer>,
  CartPanel: ({ open, children, onClose }) => open ? <div className="jelly-boutique-cart-overlay" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><aside className="jelly-boutique-cart-panel" role="dialog" aria-modal="true" aria-label="Boutique cart"><button type="button" aria-label="Close cart" onClick={onClose}>Close ×</button>{children}</aside></div> : null,
  CollectionPage: ({ products, categories, selectedCategory, allHref, categoryHref }) => <main className="jelly-boutique-collection"><header><p className="jelly-boutique-kicker">The seasonal edit</p><h1>Objects with a story.</h1><p>Curated goods for slower, more beautiful days.</p></header><nav aria-label="Product categories"><a className={!selectedCategory ? "active" : ""} href={allHref}>All pieces</a>{categories.map((category) => <a className={selectedCategory === category ? "active" : ""} key={category} href={categoryHref(category)}>{category}</a>)}</nav><div className="jelly-boutique-product-grid">{products.map((product) => <a key={product.id} href={product.href} className="jelly-boutique-product"><div><img src={product.imageUrl} alt="" />{product.soldOut ? <span>Sold out</span> : null}</div><p>{product.category}</p><h2>{product.name}</h2><strong>{product.price}</strong></a>)}</div></main>,
  ProductPage: ({ product, price, availableText, options, backHref, variantAvailable, requiredMissing, added, onSelectOption, onAddToCart }) => <main className="jelly-boutique-product-page"><a href={backHref} className="jelly-boutique-back">← Back to collection</a><div className="jelly-boutique-product-detail"><div className="jelly-boutique-product-image"><img src={product.imageUrl} alt={product.name} /></div><div className="jelly-boutique-product-copy"><p className="jelly-boutique-kicker">{product.category}</p><h1>{product.name}</h1><p className="jelly-boutique-price">{price}</p><p>{product.description}</p>{options.map((option) => <fieldset key={option.id}><legend>{option.name}{option.required ? " *" : ""}</legend><div>{option.values.map((value) => <button type="button" key={value.id} aria-pressed={value.selected} onClick={() => onSelectOption(option.id, value.id)}>{value.label}</button>)}</div></fieldset>)}<p className="jelly-boutique-availability">{availableText}</p><button type="button" disabled={!variantAvailable || requiredMissing} onClick={onAddToCart}>{added ? "Added to bag" : "Add to bag"}</button></div></div></main>,
  SearchPage: ({ query, results, shopHref }) => <main className="jelly-boutique-collection jelly-boutique-search-page"><header><p className="jelly-boutique-kicker">A considered search</p><h1>{query ? `Found for “${query}”` : "Search the collection"}</h1><p>{results.length ? `${results.length} pieces to explore.` : "Try a different word or browse the full collection."}</p></header>{results.length ? <div className="jelly-boutique-product-grid">{results.map((product) => <a key={product.id} href={product.href} className="jelly-boutique-product"><div><img src={product.imageUrl} alt="" /></div><p>{product.category}</p><h2>{product.name}</h2><strong>{product.price}</strong></a>)}</div> : <a href={shopHref} className="jelly-boutique-back">Browse all pieces →</a>}</main>,
  CartPage: ({ lines, subtotal, shopHref, checkoutHref, onDecrease, onIncrease }) => <main className="jelly-boutique-collection jelly-boutique-cart-page"><header><p className="jelly-boutique-kicker">Your edit</p><h1>Held for you.</h1><p>{lines.length ? "A quiet moment before you checkout." : "Your bag is currently empty."}</p></header>{lines.length ? <><div className="jelly-boutique-cart-lines">{lines.map((line) => <article key={line.id}><img src={line.imageUrl} alt="" /><div><p>{line.productName}</p><strong>{line.variantName}</strong>{line.options.map((option) => <small key={option}>{option}</small>)}<div className="jelly-boutique-cart-quantity"><button type="button" aria-label={`Remove one ${line.productName}`} onClick={() => onDecrease(line.id)}>−</button><span>{line.quantity}</span><button type="button" aria-label={`Add one ${line.productName}`} disabled={!line.canIncrease} onClick={() => onIncrease(line.id)}>+</button></div></div><b>{line.lineTotal}</b></article>)}</div><div className="jelly-boutique-cart-total"><span>Subtotal</span><strong>{subtotal}</strong><a href={checkoutHref}>Continue to checkout →</a></div></> : <a href={shopHref} className="jelly-boutique-back">Browse all pieces →</a>}</main>,
  CheckoutPage: ({ children }) => <div className="jelly-boutique-checkout-page"><div className="jelly-boutique-kicker">A considered checkout</div>{children}</div>,
  OrderPage: ({ children }) => <div className="jelly-boutique-order-page">{children}</div>,
  ContentPage: ({ children }) => <div className="jelly-boutique-content-page">{children}</div>,
};
