"use client";

import { useState } from "react";
import { CheckCircle2, ExternalLink } from "lucide-react";
import Link from "next/link";
import { useShop } from "@/contexts/shop-context";

export default function StorePage() {
  const { state, repository } = useShop();
  const store = state.stores.find((item) => item.id === state.activeStoreId)!;
  const [saved, setSaved] = useState(false);
  function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); repository.saveStore({ ...store, tagline: String(data.get("tagline")), description: String(data.get("description")), bannerUrl: String(data.get("bannerUrl")), published: data.get("published") === "on", theme: { ...store.theme, accent: String(data.get("accent")), background: String(data.get("background")), displayFont: String(data.get("displayFont")) as "serif" | "rounded" } }); setSaved(true); }
  return <div className="admin-page narrow-page"><header className="page-head split-head"><div><span className="page-kicker">Store design</span><h1>Make it feel like yours</h1><p>A few strong choices shape the whole storefront.</p></div><Link className="button button-secondary" href={`/${store.slug}`}><ExternalLink size={16} /> Preview store</Link></header>{saved ? <div className="success-banner"><CheckCircle2 size={18} /> Storefront updated</div> : null}<form className="admin-form" onSubmit={save} onChange={() => setSaved(false)}><section className="form-card"><div className="form-card-title"><div><span>Voice</span><h2>Your storefront opening</h2></div></div><div className="field-grid"><label className="field field-wide"><span>Tagline</span><input name="tagline" defaultValue={store.tagline} /></label><label className="field field-wide"><span>Short story</span><textarea name="description" rows={4} defaultValue={store.description} /></label><label className="field field-wide"><span>Hero image URL</span><input name="bannerUrl" type="url" defaultValue={store.bannerUrl} /></label></div></section><section className="form-card"><div className="form-card-title"><div><span>Look</span><h2>Color and character</h2></div></div><div className="theme-fields"><label><span>Accent</span><input name="accent" type="color" defaultValue={store.theme.accent} /></label><label><span>Background</span><input name="background" type="color" defaultValue={store.theme.background} /></label><label className="field"><span>Display type</span><select name="displayFont" defaultValue={store.theme.displayFont}><option value="serif">Soft editorial</option><option value="rounded">Friendly rounded</option></select></label></div><label className="check-field"><input name="published" type="checkbox" defaultChecked={store.published} /><span><b>Store is published</b><small>Customers can visit and place mock orders.</small></span></label></section><div className="form-actions"><button className="button button-primary" type="submit">Save storefront</button></div></form></div>;
}
