"use client";

import Image from "next/image";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useState } from "react";
import { ArrowLeft, Check, LockKeyhole, PackageCheck } from "lucide-react";
import { useShop } from "@/contexts/shop-context";
import { formatMoney, type Order } from "@/lib/domain";
import { createCommerceApi } from "@/features/commerce/api/client";
import { PaymentElementCheckout } from "@/features/commerce/components/payment-element-checkout";
import { useThemePresentation } from "@/components/storefront-shell";

export function CheckoutView({ storeSlug }: { storeSlug: string }) {
  const { repository, state } = useShop();
  const [order, setOrder] = useState<Order | null>(null);
  const [error, setError] = useState("");
  const [pending, setPending] = useState(false);
  const [prepared, setPrepared] = useState<{ clientSecret: string; connectedAccountId: string; publicToken: string } | null>(null);
  const store = repository.getStoreBySlug(storeSlug);
  const cart = repository.getCartForStore(storeSlug);
  if (!store) return null;
  if (order) return <main className="flex min-h-[75vh] flex-col items-center justify-center px-6 py-20 text-center text-[var(--store-text)]"><span className="mb-6 grid size-[78px] place-items-center rounded-full border-2 border-[var(--store-text)] bg-[var(--store-accent-soft)] shadow-[6px_6px_0_var(--store-text)]"><Check /></span><p className="text-[10px] font-extrabold uppercase tracking-[.12em] text-[var(--store-accent)]">Payment accepted</p><h1 className="my-3 font-[var(--store-display,Georgia)] text-[clamp(3.5rem,8vw,7.5rem)] leading-[.86] tracking-[-.07em]">Order confirmed</h1><p className="max-w-[530px] leading-relaxed opacity-70">Thank you, {order.customerSnapshot.name.split(" ")[0]}. Your order <b>{order.number}</b> is now in the merchant’s queue.</p><div className="my-7 grid w-full max-w-[430px] grid-cols-[1fr_auto] gap-2 rounded-[16px] border border-[color-mix(in_srgb,var(--store-text)_20%,transparent)] p-5 text-left text-[10px]"><span>Total paid</span><b>{formatMoney(order.totalMinor, order.currency)}</b><span className="col-span-full">Stripe payment · {order.paymentId}</span></div><div className="flex items-center gap-5 text-[11px] font-bold"><Link className="inline-flex min-h-[50px] items-center rounded-[999px_999px_999px_14px] border-[1.5px] border-[var(--store-text)] bg-[var(--store-text)] px-5 text-[var(--store-bg)]" href={`/${store.slug}/order/${order.id}`}>View order</Link><Link href={`/${store.slug}/shop`}>Keep shopping</Link></div></main>;
  const lines = cart?.items.map((item) => { const product = state.products.find((entry) => entry.variants.some((variant) => variant.id === item.variantId)); const variant = product?.variants.find((entry) => entry.id === item.variantId); return product && variant ? { item, product, variant } : null; }).filter(Boolean) ?? [];
  const subtotal = lines.reduce((sum, line) => sum + (line!.item.unitPriceMinor ?? line!.variant.priceMinor) * line!.item.quantity, 0);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!cart || !store) return; setPending(true); setError(""); const data = new FormData(event.currentTarget); try { const customer = { name: String(data.get("name")), email: String(data.get("email")), phone: String(data.get("phone")), address: { line1: String(data.get("line1")), line2: String(data.get("line2") || "") || undefined, city: String(data.get("city")), region: String(data.get("region")), postalCode: String(data.get("postalCode")), country: "IN" } }; const api = createCommerceApi({ baseUrl: process.env.NEXT_PUBLIC_STORE_EDITOR_API_URL ?? "http://localhost:3001" }); const items = cart.items.map((item) => { const product = state.products.find((entry) => entry.variants.some((variant) => variant.id === item.variantId)); return { ...item, configurationSelections: item.configurationSelections?.map((selection) => { const option = product?.options?.find((candidate) => candidate.id === selection.optionId); const value = option?.values.find((candidate) => candidate.id === selection.valueId); return { ...selection, optionName: option?.name ?? selection.optionId, valueLabel: value?.label ?? selection.valueId, priceAdjustmentMinor: value?.priceAdjustmentMinor ?? 0 }; }) }; }); const attempt = await api.createAttempt(store.id, { cartKey: cart.id, currency: store.currency.toUpperCase(), items, customerSnapshot: customer, deliverySnapshot: customer.address }); const payment = await api.preparePayment(store.id, attempt.attemptId); setPrepared(payment); } catch (caught) { setError(caught instanceof Error ? caught.message.replaceAll("_", " ") : "Checkout failed"); } finally { setPending(false); } }
  if (!cart || lines.length === 0) return <main className="flex min-h-[75vh] flex-col items-center justify-center gap-4 px-6 text-center text-[var(--store-text)]"><PackageCheck size={36} /><h1 className="font-[var(--store-display,Georgia)] text-5xl">Your cart is empty</h1><p className="opacity-70">Add a treat before heading to checkout.</p><Link className="inline-flex min-h-[50px] items-center rounded-[999px_999px_999px_14px] bg-[var(--store-text)] px-5 font-extrabold text-[var(--store-bg)]" href={`/${store.slug}/shop`}>Browse the shop</Link></main>;
  return <main className="checkout-page"><Link className="product-back" href={`/${store.slug}/shop`}><ArrowLeft size={16} /> Keep shopping</Link><header><span>Secure card checkout</span><h1>Almost yours.</h1><p>Enter delivery details and pay securely by card.</p></header><div className="checkout-grid"><div className="checkout-form"><form onSubmit={submit}><section><span className="checkout-step">01</span><h2>Your details</h2><div className="field-grid"><label className="field"><span>Name</span><input name="name" autoComplete="name" required /></label><label className="field"><span>Email</span><input name="email" type="email" autoComplete="email" required /></label><label className="field field-wide"><span>Phone</span><input name="phone" type="tel" autoComplete="tel" required /></label></div></section><section><span className="checkout-step">02</span><h2>Delivery address</h2><div className="field-grid"><label className="field field-wide"><span>Address line</span><input name="line1" autoComplete="street-address" required /></label><label className="field field-wide"><span>Apartment, suite, etc. (optional)</span><input name="line2" /></label><label className="field"><span>City</span><input name="city" autoComplete="address-level2" required /></label><label className="field"><span>State</span><input name="region" autoComplete="address-level1" required /></label><label className="field"><span>Postal code</span><input name="postalCode" autoComplete="postal-code" required /></label></div></section>{error ? <p className="checkout-error" role="alert">{error}</p> : null}{prepared ? null : <button type="submit" className="store-button wide" disabled={pending}><LockKeyhole size={17} /> {pending ? "Preparing payment…" : "Continue to card payment"}</button>}</form>{prepared ? <PaymentElementCheckout clientSecret={prepared.clientSecret} connectedAccountId={prepared.connectedAccountId} onPaid={() => window.location.assign(`/${store.slug}/order/${prepared.publicToken}`)} /> : null}</div><aside className="checkout-summary"><h2>Order summary</h2>{lines.map((line) => line && <div className="checkout-line" key={line.variant.id}><span className="checkout-thumb"><Image src={line.product.imageUrl} alt="" fill sizes="64px" /><b>{line.item.quantity}</b></span><div><strong>{line.product.name}</strong><span>{line.variant.name}</span></div><b>{formatMoney(line.variant.priceMinor * line.item.quantity, store.currency)}</b></div>)}<div className="checkout-totals"><div><span>Subtotal</span><b>{formatMoney(subtotal, store.currency)}</b></div><div><span>Shipping</span><b>{formatMoney(store.shippingMinor, store.currency)}</b></div><div><span>Total</span><b>{formatMoney(subtotal + store.shippingMinor, store.currency)}</b></div></div></aside></div></main>;
}

export default function CheckoutPage() {
  const { storeSlug } = useParams<{ storeSlug: string }>();
  const { repository } = useShop();
  const { shell, settings } = useThemePresentation();
  const store = repository.getStoreBySlug(storeSlug);
  if (!store) return null;
  const Checkout = shell.CheckoutPage;
  return <Checkout store={{ name: store.name, slug: store.slug, tagline: store.tagline, logoUrl: store.logoUrl }} settings={settings}><CheckoutView storeSlug={storeSlug} /></Checkout>;
}
